"""add phone number to post

Revision ID: 009da9ae5614
Revises: 51920a06f9eb
Create Date: 2023-06-12 15:07:52.235327

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '009da9ae5614'
down_revision = '51920a06f9eb'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('phone_number', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'phone_number')
    # ### end Alembic commands ###
